### ISSUE TITLE
Website suggestions and typos

### ISSUE THREAD

**Issue by t-mitchell** [sun-umn/NCVX_Documentation#1]
I have some minor suggestions and found a bunch of small typos, but I'll let you make the changes since perhaps you won't agree with some of these.  But fixing all of these things shouldn't take long at all.  

- [x] On the home page, consider deleting the big warning block at the top because: 
    - It might scare off users as it's the first thing users will see and it's sort of scary looking.
    - It's mostly redundant: (1) The AGPL license already says that the software comes with no warranty / use at your own risk, (2) we already have the contact/feedback instructions below under "Contact", and (3) the info for reporting bugs is also already under "Contact".  
    - The "under active development" is already strongly implied by the rest of the website.
    - You could move the "We are always looking for contributors and collaborators." sentence to somewhere under the Contact header or a new header, e.g., "Interested in contributing?"
- [x] Intro page under Key Features: change to "can handle general NCVX, nonsmooth, constrained problems" to "nonsmooth NCVX problems with nonsmooth constraints" (same wording we used in the abstract and elsewhere)
- [x] Install page: like readme, maybe add the step 0 for installing Anaconda???
- [x] NCVX New Options: 
    - [x] "Weak-Wolfe" to "weak-Wolfe"
    - [x] "search_direction_rescaling" would be more correct than "searching_direction_rescaling" but I'm not sure we should change this now, as it also means changing the code a tiny bit.  
    - [x] If some of these settings are still experimental, you might consider not documenting those publicly for the time being.  Alternatively, consider moving all experimental settings to their own (sub)section where you can say that these settings are still in development/experimental and may change or be removed in future releases; this could still be on the same "NCVX New Options" page.
    - [x] globalAD: missing period before "Please check"
- [x] General: should we make links actual links instead of doing things like "GRANSO (http://www.timmitchell.com/software/GRANSO/)"?
- [x] Dictionary Learning: should "Bai, Ju" be "Ju Bai" for consistency with the other authors?  Same issue with other papers in the examples.  Since these aren't properly formatted references, maybe it's easiest to only give last names and then have a real hyperlink to the specific paper/preprint.
- [x] Sphere manifold: this isn't exactly the same problem as the manopt one, right?  They say that they min -x^T A x, so the sign is different. 
- [x] Tip 1: "modify the install directory of PyGRANSO" and then at the end: "for the tutorials."
- [x] Tip 2: delete comma after "... device is CPU)"
- [x] Tip 3: "has a required format" and later, delete "please" since the user must return `None`.  
- [x] Tip 3: for the advanced users paragraph: "three values" should be "six values", right?  If you want, you could mention that this advanced mode also allows one to mix AD gradient computation with explicitly computed gradients (but maybe we want to leave mentioning that to a later release).
- [x] Tip 5: the meaning of this tip is unclear to me.  Can you please edit this some more?
- [x] Citation page: the formatting we have in the readme is much easier to absorb so I suggest duplicating that layout here as well.    

BTW, are the settings pages automatically made from the source code or do you have to do these manually?

**Comment by Buyun-Liang** [comment]
Updated most of them.  But I am not quite understand the following tasks:

> If some of these settings are still experimental, you might consider not documenting those publicly for the time being. Alternatively, consider moving all experimental settings to their own (sub)section where you can say that these settings are still in development/experimental and may change or be removed in future releases; this could still be on the same "NCVX New Options" page.

Not quite understand it. What do you mean by "their own (sub)section"? Should we keep the experimental settings in "NCVX New Options" page or not?

> General: should we make links actual links instead of doing things like "GRANSO (http://www.timmitchell.com/software/GRANSO/)"?

What is actual link?  Can you point me which places need to be changed?

> Tip 5: the meaning of this tip is unclear to me. Can you please edit this some more?

Just updated it. But I realized we should change the format automatically, instead of asking users to specify double_precision. 

See dictionary learning example "opts.x0 = torch.from_numpy(x0).to(device=device, dtype=torch.double)":

Instead of asking users to move their data to certain device and specify data format, we should transform it automatically.

> BTW, are the settings pages automatically made from the source code or do you have to do these manually?

I manually pasted all settings into the rst file, and use **Spinx** (https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html) to generate the doc website.

**Comment by Buyun-Liang** [comment]
Since I updated the PyGRANSO source code, I would like to remove the previous release and make a new initial release after we finalizing website and paper

**Comment by t-mitchell** [comment]
> Since I updated the PyGRANSO source code, I would like to remove the previous release and make a new initial release after we finalizing website and paper

Sure.

**Comment by Buyun-Liang** [comment]
Regarding my previous reply:

> Just updated it. But I realized we should change the format automatically, instead of asking users to specify double_precision.
> See dictionary learning example "opts.x0 = torch.from_numpy(x0).to(device=device, dtype=torch.double)":
> Instead of asking users to move their data to certain device and specify data format, we should transform it automatically.

Seems we cannot do it, because user has to provide combined_fn, the computation inside it must be in the correct format and device

**Comment by t-mitchell** [comment]
Would it be easier to discuss the few remaining few issues over Zoom?

**Comment by Buyun-Liang** [comment]
Sure, are you available now?

**Comment by t-mitchell** [comment]
> Sure, are you available now?

Yes.

**Comment by Buyun-Liang** [comment]
Encode the optimization variables and objective and constraint functions.

**Comment by Buyun-Liang** [comment]
I'll keep options `globalAD` and `QPsolver`,  as `checkH0` and `scaleH0` are used in GRANSO, which has the same style.

**Comment by Buyun-Liang** [comment]
Updated the website and examples in source code based on our discussion today. The previous tip 5 was moved to the comments of each examples.

**Comment by t-mitchell** [comment]
> I'll keep options `globalAD` and `QPsolver`, as `checkH0` and `scaleH0` are used in GRANSO, which has the same style.

OK, that's fine.  FYI, I recall now why GRANSO ended up with a mix of option naming conventions.  In the beginning, I was trying to keep some consistency with Michael's HANSO code, but at some point, I just decided to use the underscore convention for all new parameters because they had long names.  Probably I should have just used one convention from the get go, but oh well.
